### ISSUE TITLE
Add `Cachable` derive macros

### ISSUE THREAD

**Issue by AndreyErmilov** [rambler-digital-solutions/actix-cache#1]
For a cached structure, you have to implement `Cacheable` trait
```rust
impl Cacheable for QueryNothing { 
    fn cache_key(&self) -> String {
        format!("database::QueryNothing::id::{}", self.id.map_or_else(
            || "None".to_owned(), |id| id.to_string())
        )
    }
}
```
This is similar to boilerplate code, and we could use derived macros instead of implementing them ourselves
```rust
#[derive(Cachable, Serialize, Deserialize, Debug)]
struct QueryNothing {
    id: Option<i32>,
}
```

@singulared What do you think about an interface?

**Comment by singulared** [comment]
`#[derive(Cachable)]` should be enough.
In my opinion, we should use `serde` for `cache_key` generation.
Something like `serde_urlencoded` for the first implementation will be enough.

**Comment by AndreyErmilov** [comment]
We also decided to add ttl and state_ttl macros. 
Message will be
```rust
#[derive(Cacheable, Serialize)]
#ttl(60)
#stale_ttl(120)
struct Message {
    id: i32,
    alias: String,
}
```
@singulared Let me know if something is wrong

**Comment by singulared** [comment]
```rust
​#[derive(Cacheable, Serialize)]
#[cache_ttl(​60​)]
#​[cache_stale_ttl(​120​)]
#[cache_version(2)]
​struct​ ​Message​ {
    id: ​i32​,
    alias: ​String​,
}
```
I think add more explicit naming will be better.
