### ISSUE TITLE
Add prefix into Cacheable::cache_key

### ISSUE THREAD

**Issue by singulared** [rambler-digital-solutions/actix-cache#13]
A good idea is to add a prefix into Cacheable::cache_key with a type name, same as we add it in metrics.
https://doc.rust-lang.org/std/any/fn.type_name.
https://github.com/rambler-digital-solutions/actix-cache/blob/56ba03944e21aef8585e00a383745c7205d9f021/src/cache.rs#L161

**Comment by AndreyErmilov** [comment]
closes #16
