### ISSUE TITLE
Add more actix-web + diesel practical examples.

### ISSUE THREAD

**Issue by singulared** [rambler-digital-solutions/actix-cache#14]

**Comment by AndreyErmilov** [comment]
- [x] check if examples can be crates with separate dependencies from the actix-cache
- [ ] add base project (blog?)
- [ ] add database migrations
- [ ] run example in CI/CD

**Comment by AndreyErmilov** [comment]
This task is being worked on in a separate [repository](https://github.com/AndreyErmilov/actix-blog)
