### ISSUE TITLE
Hide Cache behind a feature flag

### ISSUE THREAD

**Issue by zhiburt** [rambler-digital-solutions/actix-cache#22]
What if `Cache` will be hidden by feature

```rust
#[cfg(feature = "redis")]
type Cache = CacheActor<RedisBackend>;

#[cfg(feature = "memcached")]
type Cache = CacheActor<Memcashed>;

#[cfg(feature = "default")]
type Cache = CacheActor<Heap>;
```

Potentially it could reduce a binary size as well as it allows not writing `Cache::<Redis>::new()`

Currently this not as valuable though, but if there plans to add more then 1 back-end may be

**Comment by AndreyErmilov** [comment]
Hey @zhiburt! Thanks! Yeah, why not. We could add a feature flag right now.
